spring.application.name=restApiJpa
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/restJpa

# Database Credentials
spring.datasource.username=postgres
spring.datasource.password=000011

# PostgreSQL Driver Class
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DDL Auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
